export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_CLEAR = "FETCH_USER_CLEAR";

export const FETCH_CONTENT = "FETCH_CONTENT"
export const FETCH_CONTENT_SUCCESS = "FETCH_CONTENT_SUCCESS"
export const FETCH_CONTENT_CLEAR = "FETCH_CONTENT_CLEAR"
export const FETCH_CONTENT_FEEDS = "FETCH_CONTENT_FEEDS";
export const FETCH_CONTENT_SYS = "FETCH_CONTENT_SYS";